name: salsa-dicom
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab=2.2.9
  - pydicom=2.1.2
  - ipykernel=5.5.5
  - ipywidgets=7.5.1
  - panel=0.11.3
  - pandas=1.2.4
  - nodejs=15.14.0
  - matplotlib=3.4.2
  - scikit-image=0.18.1
  - pyvista=0.31.0
