name: siegvent2023
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab=2.2.9
  - pydicom=2.1.2
  - ipykernel=5.5.5
  - ipywidgets=7.5.1
  - panel=0.11.3
  - pandas=1.2.4
  - nodejs=15.14.0
  - matplotlib=3.4.2
  - scikit-image=0.18.1
  - pygmt=0.4.1
  - geopandas=0.9.0
  - pyproj=3.3.1
  - h5py=3.3.0
  - cmocean=2.0
  - rpy2=3.5.1
  - seaborn=0.11.2
